### PR TITLE
Updated package.json

### PR DESCRIPTION
**Pull request by coderReview**

### CODE REVIEW

**Comment by rpellerin** [comment]
Could you please update the tests so that they pass?

**Comment by coderReview** [comment]
Will check it out

**Comment by rpellerin** [comment]
Your PR can't be merged since the tests still do not pass. Also can you please make sure you update the documentation if need be? Thank you.

**Comment by rpellerin** [comment]
I just merged https://github.com/rpellerin/graphql-sequelize-schema-generator/pull/6 which contains all your commits but the last one. You might want to rebase your branch before I merge your PR?

**Comment by coderReview** [comment]
ok. Thanks.

**Pull request closed without merging**
